### PR TITLE
feat: oidc support

### LINKED ISSUE #1638: Login with other services
#### Description

Is your feature request related to a problem? If so, please provide a clear and concise description of the problem. E.g., "I'm always frustrated when [...]."

I have some family members who I would like to give access to but will probably result in me being constantly asked for their password. Adding support for providers like auth0 would allow me to enable sending a code via sms or email for them to enter on the page to login as an authentication method which would work better than a link if the web app is added to their home screen.

#### Desired Behavior

Allow a third party authentication service like auth0 to either login directly to the web app similar to plex or using SSO from a reverse proxy.

### PR DESCRIPTION
**Pull request by ankarhem**
#### Description
- There is no authorization of any kind, it just authenticates as a way to login / create the user. Authorizations are handled as usual per user in overseerr. So no custom scopes / roles etc.

This works when I test it with auth0 but would be nice to get some additional testing with other providers. Appreciate if I could get help setting up oidc on authelia if someone has this, or if someone could test it.

#### To-Dos

- [x] Add api docs
- [x] Clean up the code
- [x] Refactor out popup handling stuff from plex and use that for a oidc class instead of redirecting the whole page
- [x] Test with other providers
- [x] Add validation (all fields required, domain is a domain etc.) to the oidc settings in settings page
~~- [ ] Revocation logic?~~
- [x] Create account if it doesn't exist?

- [x] Successful build `yarn build`
- [x] Translation keys `yarn i18n:extract`
~~- [] Database migration (if required)~~

#### Other considerations
I considered saving the token and refresh_token and add token handling / validating it for requests, but since other login methods considers you logged in as long as you have the user id in the session I didn't.

#### Issues Fixed or Closed

- Fixes #1638

### CODE REVIEW

**Comment by ankarhem** [comment]
> Would love to see this implemented. Is this on the roadmap?

Well, this is functional. It needs to be reviewed is all.

**Comment by ayazgoff** [comment]
I just pulled this and tested it with OIDC from [Authentik](https://github.com/goauthentik/authentik). It works as intended after a few changes:
- [This regex](https://github.com/ankarhem/overseerr/blob/oidc-support/src/components/Settings/SettingsUsers/index.tsx#:~:text=/%5E(%3F!%3A%5C/%5C/)(%5Ba%2DzA%2DZ0%2D9%2D_%5D%2B%5C.)*%5Ba%2DzA%2DZ0%2D9%5D%5Ba%2DzA%2DZ0%2D9%2D_%5D%2B%5C.%5Ba%2DzA%2DZ%5D%7B2%2C11%7D%3F%24/) is overly restrictive -- it should allow for port and path specification. The [OpenID spec](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata) only requires that the OIDC issuer be a "URL using the https scheme with no query or fragment component", and for Authentik it is `https://{domain}/application/o/{application}/`
- There's a [typo](https://github.com/ankarhem/overseerr/blob/oidc-support/server/routes/auth.ts#L485) in the token request body in server/routes/auth.ts ("client_cecret").
- That same token request uses `application/json` encoding, which was being rejected by Authentik's token endpoint. As far as I can tell, [RFC6749](https://datatracker.ietf.org/doc/html/rfc6749) only requires OAuth providers to accept `application/x-www-form-urlencoded` posts.

**Comment by ankarhem** [comment]
> I just pulled this and tested it with OIDC from [Authentik](https://github.com/goauthentik/authentik). It works as intended after a few changes:
> 
>     * [This regex](https://github.com/ankarhem/overseerr/blob/oidc-support/src/components/Settings/SettingsUsers/index.tsx#:~:text=/%5E(%3F!%3A%5C/%5C/)(%5Ba%2DzA%2DZ0%2D9%2D_%5D%2B%5C.)*%5Ba%2DzA%2DZ0%2D9%5D%5Ba%2DzA%2DZ0%2D9%2D_%5D%2B%5C.%5Ba%2DzA%2DZ%5D%7B2%2C11%7D%3F%24/) is overly restrictive -- it should allow for port and path specification. The [OpenID spec](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata) only requires that the OIDC issuer be a "URL using the https scheme with no query or fragment component", and for Authentik it is `https://{domain}/application/o/{application}/`
> 
>     * There's a [typo](https://github.com/ankarhem/overseerr/blob/oidc-support/server/routes/auth.ts#L485) in the token request body in server/routes/auth.ts ("client_cecret").
> 
>     * That same token request uses `application/json` encoding, which was being rejected by Authentik's token endpoint. As far as I can tell, [RFC6749](https://datatracker.ietf.org/doc/html/rfc6749) only requires OAuth providers to accept `application/x-www-form-urlencoded` posts.

Thanks! I'll make the changes when I have the time.

**Comment by Mlitz** [comment]
Any updates on this?

**Comment by obsidiangroup** [comment]
> > I just pulled this and tested it with OIDC from [Authentik](https://github.com/goauthentik/authentik). It works as intended after a few changes:
> > ```
> > * [This regex](https://github.com/ankarhem/overseerr/blob/oidc-support/src/components/Settings/SettingsUsers/index.tsx#:~:text=/%5E(%3F!%3A%5C/%5C/)(%5Ba%2DzA%2DZ0%2D9%2D_%5D%2B%5C.)*%5Ba%2DzA%2DZ0%2D9%5D%5Ba%2DzA%2DZ0%2D9%2D_%5D%2B%5C.%5Ba%2DzA%2DZ%5D%7B2%2C11%7D%3F%24/) is overly restrictive -- it should allow for port and path specification. The [OpenID spec](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata) only requires that the OIDC issuer be a "URL using the https scheme with no query or fragment component", and for Authentik it is `https://{domain}/application/o/{application}/`
> > 
> > * There's a [typo](https://github.com/ankarhem/overseerr/blob/oidc-support/server/routes/auth.ts#L485) in the token request body in server/routes/auth.ts ("client_cecret").
> > 
> > * That same token request uses `application/json` encoding, which was being rejected by Authentik's token endpoint. As far as I can tell, [RFC6749](https://datatracker.ietf.org/doc/html/rfc6749) only requires OAuth providers to accept `application/x-www-form-urlencoded` posts.
> > ```
> 
> Thanks! I'll make the changes when I have the time.

Thanks!  I'm going to have to switch to this branch to test with Authentik as well.  I currently have a policy that when a user goes to Overseerr, authentik pulls their plex_token and passes it to Overseerr.  This "works" as long as the user has already associated their account with their Plex account.  However, if they do not have a plex account, this doesn't work. @ayazgoff  outside of the code changes you referenced, was there anything special on the Authentik side you had to do?

**Comment by ankarhem** [comment]
Fixed review comments and rebased the branch

**Comment by ados8** [comment]
Testing with Authentik and it fails the OIDC login due to exceeded threshold.
image

Jellyseerr presents an error to sign in.
image

My config is as follows:
OIDC Issuer URL: `https://auth.domain.com/application/o/jellyseerr/`
OIDC Provider Name: `Authntik`
OIDC Client ID: `generated ID from Authntik`

**Comment by obsidiangroup** [comment]
@ayazgoff can you share your Authentik configs, and @ankarhem have the changes @ayazgoff  stated been implemented?

**Comment by ankarhem** [comment]
> @ayazgoff can you share your Authentik configs, and @ankarhem have the changes @ayazgoff stated been implemented?

Yes they were addressed in ef24e30

**Comment by obsidiangroup** [comment]
Some comments.
in server/utils/oidc.ts in the getOIDCRedirectURL, you are making assumptions about the url.pathname.  This should be configurable.  For example, Authentik uses /application/o/authorize and not /authorize.

You haven't published what one should set the url to send requests back to.  If you set your redirect url to http://overseerr/api/v1/auth/oidc-callback -- you receive errors:

`{"message":"request.cookies should have required property 'oidc-state'","errors":[{"path":".cookies.oidc-state","message":"should have required property 'oidc-state'","errorCode":"required.openapi.validation"}]}`

You aren't handling correctly if they cancel the OIDC logon -- you receive an error:

image

I am stuck at this point.  I have modified oidc.ts to change the url.pathname, but not sure what the next steps should be.
@ankarhem any suggestions?

**Comment by ankarhem** [comment]
> Some comments. in server/utils/oidc.ts in the getOIDCRedirectURL, you are making assumptions about the url.pathname. This should be configurable. For example, Authentik uses /application/o/authorize and not /authorize.
> 

Right, should fetch the auth pathname from the wellknown configuration. I'll change that.

> You haven't published what one should set the url to send requests back to. If you set your redirect url to http://overseerr/api/v1/auth/oidc-callback -- you receive errors:
> 
> `{"message":"request.cookies should have required property 'oidc-state'","errors":[{"path":".cookies.oidc-state","message":"should have required property 'oidc-state'","errorCode":"required.openapi.validation"}]}`

Not sure what you mean, this should be handled automatically.

**Comment by ankarhem** [comment]
@obsidiangroup I have made the changes now (fetches auth endpoint from wellknown configuration and handles closing of the popup), please try again.

**Comment by obsidiangroup** [comment]
> > Some comments. in server/utils/oidc.ts in the getOIDCRedirectURL, you are making assumptions about the url.pathname. This should be configurable. For example, Authentik uses /application/o/authorize and not /authorize.
> 
> Right, should fetch the auth pathname from the wellknown configuration. I'll change that.
> 
> > You haven't published what one should set the url to send requests back to. If you set your redirect url to http://overseerr/api/v1/auth/oidc-callback -- you receive errors:
> > `{"message":"request.cookies should have required property 'oidc-state'","errors":[{"path":".cookies.oidc-state","message":"should have required property 'oidc-state'","errorCode":"required.openapi.validation"}]}`
> 
> Not sure what you mean, this should be handled automatically.

First, is that the correct redirect url?  In Authentik, for OIDC you specify the Redirect URL and it uses that URL to send the oidc information back. I'm not sure if I am using the correct redirect url setting.

Right now, when I select the oidc logon option, it goes [browser] -> [overseerr] -> authentik -> authentik redirects back to http://overseerr/api/v1/auth/oidc-callback?code=[code]&state=

Once this redirect happens, you receive the error:
`{"message":"request.cookies should have required property 'oidc-state'","errors":[{"path":".cookies.oidc-state","message":"should have required property 'oidc-state'","errorCode":"required.openapi.validation"}]}`
in the browser.

**Comment by obsidiangroup** [comment]
> @obsidiangroup I have made the changes now (fetches auth endpoint from wellknown configuration and handles closing of the popup), please try again.

Will try now and report back.  Thanks :)

**Comment by ankarhem** [comment]
> > @obsidiangroup I have made the changes now (fetches auth endpoint from wellknown configuration and handles closing of the popup), please try again.
> 
> Will try now and report back. Thanks :)

Regards to your question about the redirect uri, [it should be constructed in the client](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.1) (overseerr) and is being done so [here](https://github.com/sct/overseerr/pull/2792/files#diff-130f818e3acbbeb4f4d25e7781e709081f65124e3debe27c8e118066678d2805R20). If authentik has a setting for it I assume it's for only allowing certain redirect_uri's, and I suggest you try setting it to `https://your-overseerr-domain.com`, `https://your-overseerr-domain.com/api/v1/auth/oidc-callback` or leaving it blank. If you are on discord you can DM me there and we can chat.

**Comment by ankarhem** [comment]
> The problem is you are making assumptions on the location of the wellknown configuration. 

Thanks, I was under that assumption yes. The latest changes will allow paths in the oidc domain which the well-known will be appended to when fetching configuration.

**Comment by obsidiangroup** [comment]
> If you are on discord you can DM me there and we can chat.

What's your discord id?  I attempted to join the Overseerr discord but the invite doesn't work.

**Comment by ankarhem** [comment]
> > If you are on discord you can DM me there and we can chat.
> 
> What's your discord id? I attempted to join the Overseerr discord but the invite doesn't work.

ankarhem#5069

**Comment by sct** [comment]
Thank you for continuing to work on this @ankarhem. I am making some changes to the login page in #3015 that will affect this PR. But I am looking forward to working together to get this merged!

**Comment by obsidiangroup** [comment]
> Thank you for continuing to work on this @ankarhem. I am making some changes to the login page in #3015 that will affect this PR. But I am looking forward to working together to get this merged!

I am testing this PR now, and so far just from the past 24 hours, my users have noticed no problems logging in via OIDC.  Outside of a few cosmetic changes, after working with @ankarhem yesterday everything is working.

I did make a few suggestions, including a way to integrate OIDC logoff with the app's logoff.  OIDC providers typically give you a URL to call to invalidate/logoff a token/user.  So if the user is logged in via OIDC, when they logoff, this URL should be called as well.

My other suggestion comes down to roles.  When a user logs in the first time to Overseerr, an account is created for them.  This account is created with whatever default permissions that are set.  There could be a way to set an "Admin" group, so if a user belongs to said group, their account will be created with admin rights.  This could be expanded even more that you can create roles in Overseerr with whatever permissions you want a user to have, assign a group to that role, and like the admin group, whatever roles that are defined for that group are applied to the user.  This isn't as important, as it would require changes to the permissions.  But just something for down the line.

User Labels - When you view your users, Overseerr sets a tag for 'Plex User' or 'Local User'.  If the user is created via OIDC, the tag should be 'OIDC User' or something to signify how the user was created.

But hopefully, @sct you don't change too much and can merge this PR.

**Comment by ankarhem** [comment]
> Just an update, I have been using this since 10/12, and have had 69 successful logins between 10/12 and 10/18. Have had no issues with any users not being able to login. Previous users that I had imported via Plex can also log in using oidc, and there have been no issues there (overseerr didn't create a new account, request history was still there, etc). In fact, more users have used Overseerr now that the login is seemless and I have finally been able to pull the plug on Ombi.

Everything still without issues?

**Comment by lenaxia** [comment]
I've tried spinning up the oidc-support branch without much luck. 

I'm running into the issue that the protocol is wrong. Call back keeps going back to http, specifically this line: https://github.com/ankarhem/overseerr/blob/765c38b88599ad3e869bc973a3a7246a1da7c4c0/server/routes/auth.ts#L470

Despite defining https everywhere else, I still see the callback url using http. Both my ingress is https and my application url defined in overseer is https.

Rebuilding with that line hardcoded back to https. Not sure if there's a need to have it a variable like that. OIDC will reject calls for http unless the domain ends with .localhost.

**Comment by lenaxia** [comment]
hard coded both lines to https, and now hitting an error where overseer doesn't understand scope?

After granting permissions, I get sent to the callback url: 
```
https://overseerr.my.domain/api/v1/auth/oidc-callback?code=OAEoIv5K9YVExnOMWhtP7rPEUIleEXIKG_FRTYiv1qI.nl92ja7mUD1vJNxFoj1XMU_X76qKf_Ef_-ECDgNxaEc&scope=openid+profile+email&state=56539b32f7bc80ba9a7d74beafd2fc419aa6f368e3ae0cc227e36d4f7cd9f73b
```

But recieve this error
```
{"message":"Unknown query parameter 'scope'","errors":[{"path":".query.scope","message":"Unknown query parameter 'scope'"}]}
```

**Comment by obsidiangroup** [comment]
> (I'm using Authelia)
> 
> hard coded both lines to https, and now hitting an error where overseer doesn't understand scope?
> 
> After granting permissions, I get sent to the callback url:
> 
> ```
> https://overseerr.my.domain/api/v1/auth/oidc-callback?code=OAEoIv5K9YVExnOMWhtP7rPEUIleEXIKG_FRTYiv1qI.nl92ja7mUD1vJNxFoj1XMU_X76qKf_Ef_-ECDgNxaEc&scope=openid+profile+email&state=56539b32f7bc80ba9a7d74beafd2fc419aa6f368e3ae0cc227e36d4f7cd9f73b
> ```
> 
> But recieve this error
> 
> ```
> {"message":"Unknown query parameter 'scope'","errors":[{"path":".query.scope","message":"Unknown query parameter 'scope'"}]}
> ```
> 
> I've compared the callback uris to other working OIDC implementations and the callback is well formed. So I think there's something going on with how this implementation is parsing the parameters.

I wasn't having this issue.  This implementation has been working fine with Authentik.

**Comment by obsidiangroup** [comment]
> > Just an update, I have been using this since 10/12, and have had 69 successful logins between 10/12 and 10/18. Have had no issues with any users not being able to login. Previous users that I had imported via Plex can also log in using oidc, and there have been no issues there (overseerr didn't create a new account, request history was still there, etc). In fact, more users have used Overseerr now that the login is seemless and I have finally been able to pull the plug on Ombi.
> 
> Everything still without issues?

So far, no problems.  Just was hoping it would have gotten merged in.

**Comment by yeyeoke** [comment]
Hi, just found this and was just wondering - will this get merged? Would be awesome to get OIDC working!

**Comment by OwsleyJr** [comment]
> Hi, just found this and was just wondering - will this get merged? Would be awesome to get OIDC working!

We are working on changes to the login page so this most likely will not be merged until after that.

**Comment by jonathann92** [comment]
@OwsleyJr 

Are you referring to PR #3015? We haven’t seen activity since February.  Do you know if that is still in the roadmap or still being worked on?

**Comment by obsidiangroup** [comment]
Just bumping this again, any hope of getting this merged?

**Comment by modem7** [comment]
Stalebot bump

**Comment by janstadt** [comment]
Please approve and merge this.

**Comment by modem7** [comment]
Looks like this will need to be updated regardless as it's out of sync with the master branch.

**Comment by evanhfox** [comment]
Would love to see this reviewed and merged!

**Comment by b3n3w** [comment]
Would love to see this in future releases

**Comment by fabioteixei** [comment]
@sct any chance to get this aproved? I think many people want to use this feature with IDP like Authentik, Authelia, Keycloak and etc.

**Comment by lenaxia** [comment]
@ankarhem doing some more testing and it looks like it works with authentik, but there are some additional OIDC issues that aren't addressed in your implementation, and thus do not work with Authelia.

Specifically, you are missing support for `scope`, and `error` in the OIDC response. I have had to add this to `overseerr-api.yaml / oidc-callback`:

```
  /auth/oidc-callback:
    get:
      parameters:
        - in: query
          name: scope
          required: false
          allowReserved: true
          schema:
            type: string
            example: 'openid email profile'
        - in: query
          name: error
          required: false
          schema:
            type: string
        - in: query
          name: error_description
          required: false
          schema:
            type: string
```

This also addresses an additional issue which is that Authelia includes `scope` in the callback request. Because it wasn't defined previously it would throw an error, and when it was defined, it complained that it was malformed because the string contained `+` for spaces (e.g. `openid+email+profile`. This is due to `express-openapi-validator` enforcing strict url formatting which does not allow reserved characters like `+`.

However now I'm stuck in an infinite loop on the final callback `https://$DOMAIN/api/v1/auth/oidc-callback?code=authelia_ac_HASH&scope=openid+profile+email&state=HASH`, some middleware or something is preventing the request from actually reaching the /oidc-callback endpoint (I added a `logger.info('Initiating OIDC Callback Request', {req})` statement to the beginning of `oidc-callback`  which is not being hit). 

So still working to debug through this.

**Comment by lenaxia** [comment]
> Would love to see this in future releases! Is there an container image for this PR to test it ?

You can use the image I'm building for my testing: https://github.com/lenaxia/overseerr-oidc/pkgs/container/overseerr-oidc 
```docker pull ghcr.io/lenaxia/overseerr-oidc:b4256043424658626e02bd002de1d4369f541bdb```

However, it is very volatile right now as I'm trying to figure out why its not working with authelia.

**Comment by lenaxia** [comment]
Got it all fixed (holy mackerel, it was a pain). I now know more about oidc than I ever expected, and for better or worse will probably do oidc for a few other projects I've wanted it for. 

I will rebase it and either try to get it merged into this fork or open a new PR. 

In the mean time, (in about an hour), you can use the docker image I listed above `docker pull ghcr.io/lenaxia/overseerr-oidc:latest` temporarily.

**Comment by obsidiangroup** [comment]
I will give this a try. I've been running a version with OIDC support and
has been working flawlessly.

**Comment by lenaxia** [comment]
Would appreciate it. Want to make sure I didn't break authentik.

**Comment by fabioteixei** [comment]
I will try as well myself with authentik and report back here. 
Don't have the time to deploy today but I will try tomorrow.

**Comment by lenaxia** [comment]
@ankarhem I've rebased the oidc work and have updated it meet the remaining OIDC spec so it works with authelia now. If @fabioteixei or @obsidiangroup report that all is well with authentik, would you prefer me to open a PR to your fork, or are you okay with me just opening a PR directly to this repo? 

`docker pull ghcr.io/lenaxia/overseerr-oidc:latest` now pulls an up-to-date rebased oidc-enabled image.

**Comment by b3n3w** [comment]
> @ankarhem I've rebased the oidc work and have updated it meet the remaining OIDC spec so it works with authelia now. If @fabioteixei or @obsidiangroup report that all is well with authentik, would you prefer me to open a PR to your fork, or are you okay with me just opening a PR directly to this repo?
> 
> `docker pull ghcr.io/lenaxia/overseerr-oidc:oidc-support` now pulls an up-to-date rebased oidc-enabled image.
> 
> @OwsleyJr @sct Are you ready to receive these changes? You previously mentioned that you were working on changes to the login page which seems to still be in the works.

Tried your latest version with Authentik. Currently it's authenticating and then loops back to the login page of overseer. My browser logs:

``` 
authentik/api[authentik-default]: 200 GET https://authentik.xxx/api/v3/flows/executor/default-provider-authorization-explicit-consent/?query=response_type%3Dcode lient_id%3DqHkXOOIbPkt6MTGa7MeGhaXIJi9FPAjJMMMz66kV%26redirect_uri%3Dhttps%253A%252F%overseer.xxx.com%252Fapi%252Fv1%252Fauth%252Foidc-callbackcope%3Dopenid%2Bprofile%2Bemailtate%3D3ec1436c28c4864f740aee70df46f559bd48dce301410c6a1c67732845eeca78 [vendor-U84AyUBr.js:22:9257](https://authentik.xxxx/static/dist/flow/vendor-U84AyUBr.js)

authentik/stages/redirect: redirecting to url from server https://overseer.xxx/api/v1/auth/oidc-callback?code=a55ab6cf96a54e779e5a782c2b8bd41a&state=3ec1436c28c4864f740aee70df46f559bd48dce301410c6a1c67732845eeca78 [vendor-U84AyUBr.js:22:9257](https://authentik.xxx/static/dist/flow/vendor-U84AyUBr.js)
authentik/ws: closed ws connection 

close { target: WebSocket, isTrusted: true, wasClean: true, code: 1001, reason: "", srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, … }
[vendor-U84AyUBr.js:22:9257](https://authentik.xxx.com/static/dist/flow/vendor-U84AyUBr.js)
authentik/ws: reconnecting ws in 400ms ```

Afterwards it is showing a `403` of overseer in the console.

Really appreciate your work !

**Comment by lenaxia** [comment]
Just to confirm, were you able to build @ankarhem's original pr and get it working, or does your current oidc setup work on other services?

**Comment by fabioteixei** [comment]
@lenaxia  I'm running your version but i dont see where to configure OIDC. Do i need to do an clean instalation of overseerr?

**Comment by lenaxia** [comment]
Clean install is not needed. Log in with your plex account and it's under settings > users > enable oidc. 

There is no env config for oidc.

**Comment by fabioteixei** [comment]
@lenaxia Thanks, my bad i did not see it. Configuring now and i will report back

**Comment by fabioteixei** [comment]
@lenaxia I have the same issue as @b3n3w.

In my case i use Authentik as an proxy for Azure AD authentication. My Flow:

1. User opens Overseerr page
2. Selects Login with authentik
3. Popup apears
4. Authentik transparently redirect towards Microsoft
5. User Authenticates with his Azure AD account
6. Microsft redirects back to Authentik
7. Authentik redirects back to Overseerr
8. Login screen apears inside the popup again to the start of the login loop.

Here some screenshots of my config on overseer and authentik as well the login steps:

image

image

image

image

image

image

image

image

image

Sorry about the language soup. I'm brazilian that lives in Québec, so i speek portuguese an my PC is in French, so i have a mix bag of Portuguese, French and English on my systems.

Maybe the error are on the configs or in Overseerr side or at Authentik. I had a hard time finding the right configs for OIDC domain on Overseerr and Redirect URL on authentik. 

Thanks

**Comment by lenaxia** [comment]
Thanks for the screencaps. 

Can you please rerun your container with LOG_LEVEL=debug env variable and then post the log contents from your container? Specifically you can search for 'oidc-callback', and 'oidc-login'. The callback one is likely the issue. If you can also provide the authentik logs would likely be helpful too.

**Comment by fabioteixei** [comment]
> Thanks for the screencaps.
> 
> Can you please rerun your container with LOG_LEVEL=debug env variable and then post the log contents from your container? Specifically you can search for 'oidc-callback', and 'oidc-login'. The callback one is likely the issue. If you can also provide the authentik logs would likely be helpful too.

Authentik Container or Overseer Container?

**Comment by lenaxia** [comment]
Overseerr container.

**Comment by fabioteixei** [comment]
[overseerr-5674884db8-6tljd_overseerr.log](https://github.com/sct/overseerr/files/13821559/overseerr-5674884db8-6tljd_overseerr.log)
 Here it is. Kinda long log so i thougt would be better to send you the whole log.

**Comment by lenaxia** [comment]
I run kubernetes too, so no worries there https://github.com/lenaxia/home-ops-prod/blob/main/cluster/apps/media/mediarequests/overseerr/helm-release.yaml

Looks like your client ID and secret may not be matching. 
```
2024-01-03T17:03:05.898Z [^[[32minfo^[[39m]: Failed OIDC login attempt {"cause":"Invalid token response: invalid_client","ip":"::ffff:10.42.2.230","body":{"error":"invalid_client","error_description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)"}}
```

I will spin up my own instance of authentik (won't have azure AD though), and see if I can get it working.

**Comment by fabioteixei** [comment]
> I run kubernetes too, so no worries there https://github.com/lenaxia/home-ops-prod/blob/main/cluster/apps/media/mediarequests/overseerr/helm-release.yaml
> 
> Looks like your client ID and secret may not be matching.
> 
> ```
> 2024-01-03T17:03:05.898Z [^[[32minfo^[[39m]: Failed OIDC login attempt {"cause":"Invalid token response: invalid_client","ip":"::ffff:10.42.2.230","body":{"error":"invalid_client","error_description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)"}}
> ```
> 
> I will spin up my own instance of authentik (won't have azure AD though), and see if I can get it working.

After your testing please validate the domain url on orverseerr if it's the one I pasted here on my config and the callback url as well on authentik. It seems kinda odd the values that I placed on those fields

**Comment by lenaxia** [comment]
I just tested with a basic Authentik implementation and it works. So it may have to do with your AD configuration. The error is pretty clear `2024-01-03T17:01:16.299Z [^[[32minfo^[[39m]: Failed OIDC login attempt {"cause":"Invalid token response: invalid_client","ip":"::ffff:10.42.2.230","body":{"error":"invalid_client","error_description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)"}}`, it looks like the client name is not correct, so please check that your client name and client secret match between authentik and overseerr.

image

image


image

Authentik authenticating
image

You will see the overseerr UI show up briefly in the pop up before it closes itself
image

**Comment by fabioteixei** [comment]
@lenaxia 

I think we need to documment this well (by we i mean you guys 😋 ) 
I just changed the redirect (Callback URL) to * and is working now with my Azure AD authentication. So your implementation works, it's a matter of configuring it correctly and to do so we need good documentation.

Here are my configs:
Overseerr:
image

On Overseerr we need to check the box to enable the new method so the user are provisoned just in time and dont need to import it before. As we see here the user is newly created as an local user using the email configured on authentik

image

Authentik:
image

On authentik i used the * callback url witch is not the right way of doing this for security reasons, we need to poing the right URL, so if we can document this well i think we will be good to go.

**Comment by lenaxia** [comment]
Yeah oidc definitely has a learning curve (less than kubernetes though 😆). 

Your callback url should point to your overseer instance, so it should be something like https://overseerr.domain.com/api/v1/oidc-callback.

**Comment by fabioteixei** [comment]
So @lenaxia and @sct any chance to see this merged on the official branch?

Thanks

**Comment by lenaxia** [comment]
I opened a PR to @ankarhem 's fork but happy to just open one directly here too if I dont hear from them.

**Comment by b3n3w** [comment]
> Yeah oidc definitely has a learning curve (less than kubernetes though 😆).
> 
> Your callback url should point to your overseer instance, so it should be something like https://overseerr.domain.com/api/v1/auth/oidc-callback.

After changing the redirect URL to `.*` as @fabioteixei mentioned, the authentik login works now for me :)

**Comment by lenaxia** [comment]
@b3n3w gonna strongly discourage use of a wildcard like that for oidc. That means that after logging in, a user could be directed to any site, including a malicious one. Please see if you can format your callback url to something like this: `https://overseerr.domain.com/api/v1/auth/oidc-callback`, otherwise I'd recommend you not expose your overseerr instance outside your network.

**Comment by lenaxia** [comment]
Opened a PR to this repo as I hadn't heard back from @ankarhem, code is rebased and works with Authelia and Authentik.

**Comment by ankarhem** [comment]
I left this with no intention on pursuing it further, as I tried over like 1,5 years keeping it up to date and working to get it merged. I didn't get the impression it was going anywhere so I left it, in case someone like youself would pick it up.

**Comment by lenaxia** [comment]
> I left this with no intention on pursuing it further, as I tried over like 1,5 years keeping it up to date and working to get it merged. I didn't get the impression it was going anywhere so I left it, in case someone like youself would pick it up.

Absolutely happy to pick up the torch. And just want to say how much I appreciate the work to get started. First time getting my hands dirty in OIDC code for me, so this was a great learning experience for me, and I'm hoping to implement it in other projects now too.

**Comment by b3n3w** [comment]
> @b3n3w gonna strongly discourage use of a wildcard like that for oidc. That means that after logging in, a user could be directed to any site, including a malicious one. Please see if you can format your callback url to something like this: `https://overseerr.domain.com/api/v1/auth/oidc-callback`, otherwise I'd recommend you not expose your overseerr instance outside your network.

Highly appreciate your explanation!

**Comment by volitank** [comment]
Hello, I am setting this up with Authentik and I'm getting the same `Client authentication failed` issue. if I use `.*` it works though I'd rather not use it.

```
2024-03-09T04:26:26.122Z [info]: OIDC callback initiated {"req":{"method":"GET","url":"/oidc-callback?code=477832aa79e248b3851a4e49be5d9880&state=1b1edd509ae4e561af3a51fcfde2be51e5034992e1510e382a061d75645c357f","headers":{"host":"request.domain.tld","x-real-ip":"10.0.2.101","x-real-port":"54970","x-forwarded-host":"request.domain.tld:54970","x-forwarded-server":"request.domain.tld","x-forwarded-port":"54970","x-forwarded-for":"10.0.2.101","x-forwarded-proto":"https","x-forwarded-ssl":"on","connection":"close","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","dnt":"1","sec-gpc":"1","upgrade-insecure-requests":"1","sec-fetch-dest":"document","sec-fetch-mode":"navigate","sec-fetch-site":"same-site","cookie":"oidc-state=1b1edd509ae4e561af3a51fcfde2be51e5034992e1510e382a061d75645c357f"},"remoteIp":"10.0.2.101"}}
2024-03-09T04:26:26.123Z [info]: OIDC callback without scope 
2024-03-09T04:26:26.537Z [info]: Failed OIDC login attempt {"cause":"Invalid token response: invalid_client","ip":"::ffff:10.89.5.13","body":{"error":"invalid_client","error_description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)"}}
```

**Comment by volitank** [comment]
Alright well I figured it out by checking Authentik's logs. Overseerr was actually sending http instead of https, since overseerr is behind a reverse proxy I had to enable the following setting, which should have already been enabled.

screenshot

**Comment by lmaced0** [comment]
This is what I'm getting when trying this with Authentik. Any clues why this is failing?

When I click on the OAuth option it goes through Authentik and goes back to the same Overseer login screen.

`2024-12-04T00:12:34.323Z [info]: Failed OIDC login attempt {"cause":"Invalid JWT: email_verified is a required field","ip":"10.0.10.66","idToken":"XXXX"}`

**Pull request closed without merging**
