### PR TITLE
docs(reverse-proxy): Add note for bundled sample SWAG (#681) [skip ci]

### PR DESCRIPTION
**Pull request by Roxedus**
#### Description

The example is currently bundled in SWAG, change wording to enable the subdomain the same way as the other samples

### CODE REVIEW

**Review by samwiseg0 — APPROVED** [review]
Thanks!

**Review by samwiseg0 — APPROVED** [review]
This is better!

**Comment by samwiseg0** [comment]
@all-contributors please add @Roxedus for docs

**Comment by sct** [comment]
@all-contributors please add @Roxedus for docs

**Comment by sct** [comment]
lies! Try again!

**Comment by sct** [comment]
@all-contributors please add @Roxedus for docs

**Pull request merged**
