### PR TITLE
feat: add korean locale

### PR DESCRIPTION
**Pull request by jshsakura**
#### Description
I love Overseerr!
The lack of a Korean locale has always been a pain in the ass.
I am not a professional translator, but I added ko.json to express natural expressions as much as possible and to write ambiguous or confused phrases in English.
Hopefully it will be reflected in the release.

#### To-Dos
- [x] Successful build `yarn build`
- [x] Translation keys `yarn i18n:extract`
- [ ] Database migration (if required)

#### Issues Fixed or Closed

- Fixes #XXXX

### CODE REVIEW

**Comment by jshsakura** [comment]
Oh sorry!
I think I missed it, but I'll check it out!

**Comment by SoundwaveUwU** [comment]
> all language contributions must be made through our [Weblate](https://hosted.weblate.org/projects/overseerr/#languages).

This information should be in README.

**Comment by sct** [comment]
> > all language contributions must be made through our [Weblate](https://hosted.weblate.org/projects/overseerr/#languages).
> 
> 
> 
> This information should be in README.
> 
> 
> 
> 

It is.

**Comment by jshsakura** [comment]
Weblate translations have been processed, but none have been approved yet.
Can I just wait like this?
am i missing something?

**Comment by jshsakura** [comment]
thank you I thought Weblate required a separate authorization request. 
checked the Weblate menu, but there doesn't seem to be anything I can do. 
I always support you for your hard work!! 🤗

**Comment by sct** [comment]
Nope, I just had to merge the PR. Keep in mind though, we haven't yet added support for Korean in the actual app. We need to add it to the language dropdown selector. Ill try to get to that today as well but no promises 😭

**Pull request closed without merging**
