### PR TITLE
feat: Tautulli integration

### LINKED ISSUE #2103: Tautulli Integration with Overseerr
#### Description

Watch statistics for media and users from Tautulli would be very beneficial when it comes to managing media within Overseerr.

#### Desired Behavior

A link to the Tautulli page for the media/user or showing statistics from Tautulli directly in Overseerr.

#### Additional Context

The goal of the integration would be to help understand what media is getting watched and what media users are requesting vs. what they are actually watching.

### PR DESCRIPTION
**Pull request by TheCatLady**
#### Description

Adds Tautulli integration to Overseerr.  Anyone can view the "Recently Watched" slider on their own profile, but only admins can view the data in the media management slideover and on other user profiles.

Also makes the following tweaks/changes:
- Link user names to user profiles in issue & request blocks
- Modifies the "view" button in issue blocks in the media management slideover to match buttons of request blocks
- Restrict access to "Mark as Available" / "Clear Data" buttons in media management slideover to admins only, and group them together in an "Advanced" section at the bottom of the slideover
- Instead of having text clarifying that the "Mark as Available" buttons will affect all seasons for series, display more descriptive button text
- Only display requests which have not been declined in media management slideover (similar to how we only display open issues)
- Do not display "Requests" section in media management slideover if there are none to show
- Only display cog button to open slideover on media pages if there is media to manage (otherwise, the slideover doesn't offer any functionality)

**Note:** Requires Tautulli v2.8.1+

#### Screenshot (if UI-related)

image
image
image

#### To-Dos

- [x] Add Tautulli settings
- [x] Add API endpoints to fetch watch history data from Tautulli
- [x] Display media watch history in media management slideover
- [x] Display user watch history on user profile pages
- [x] Successful build `yarn build`
- [x] Translation keys `yarn i18n:extract`

#### Issues Fixed or Closed

- Closes #2103

### CODE REVIEW

**Comment by JonnyWong16** [comment]
Using `get_user_watch_time_stats` and `get_item_watch_time_stats` might be better than retrieving the last 100 history entries from `get_history`. The former allows you to get a total for all time (`query_days=0`).

Pending merging of this commit into the Tautulli `master` branch.

https://github.com/Tautulli/Tautulli/commit/094b2211c3c300ef3bf6d9a47acb8938fb55fc31

**Comment by TheCatLady** [comment]
> Using `get_user_watch_time_stats` and `get_item_watch_time_stats` might be better than retrieving the last 100 history entries from `get_history`. The former allows you to get a total for all time (`query_days=0`).
> 
> Pending merging of this commit into the Tautulli `master` branch.
> 
> [Tautulli/Tautulli@094b221](https://github.com/Tautulli/Tautulli/commit/094b2211c3c300ef3bf6d9a47acb8938fb55fc31)

Ooh, awesome!  Thanks as always, @JonnyWong16 😻

**Comment by JonnyWong16** [comment]
Tautulli API changes have been merged into v2.8.1.

**Review by sct — APPROVED** [review]
Awesome :) Let's give it a go and get some feedback from people.

**Pull request merged**
