### PR TITLE
feat: Continue Watching

### PR DESCRIPTION
**Pull request by cedric-bour**
#### Description

I created new page for list tv show already looked when is a new season are available and if tv show not in request list

This code can be optimized I think :p

#### Screenshot (if UI-related)

Capture d’écran 2023-08-03 à 23 55 19

Capture d’écran 2023-08-03 à 23 55 33

### CODE REVIEW

**Comment by cedric-bour** [comment]
I see fix for « Availability Sync »
Is not good for me 😂
I want keep history in overseerr
Please add option for disable this feature or add new value for « view » flag

**Comment by sct** [comment]
> I see fix for « Availability Sync » Is not good for me 😂 I want keep histories in overseerr I create new value in db for keep already downloaded Working in progress

Don't put in the effort as its already done in this PR: https://github.com/sct/overseerr/pull/3460 which will be merged at some point.

As for this PR, I don't think this belongs in Overseerr. Sonarr normally grabs new seasons automatically when a show is monitored, and they will appear in Plex.

**Comment by cedric-bour** [comment]
> > I see fix for « Availability Sync » Is not good for me 😂 I want keep histories in overseerr I create new value in db for keep already downloaded Working in progress
> 
> Don't put in the effort as its already done in this PR: #3460 which will be merged at some point.
> 
> As for this PR, I don't think this belongs in Overseerr. Sonarr normally grabs new seasons automatically when a show is monitored, and they will appear in Plex.

Personally, I don't use Sonarr. I've created my own script that fetches TV shows and movies. I just think it would be much better to have this view in Overseerr, as I prefer to have all graphical interactions with Overseerr. I don't want to manage my lists of movies and TV shows in two different programs... especially since I don't necessarily want to download all available seasons. Anyway, I'll incorporate the work from the MR for the deleted status. Thank you.

**Comment by sct** [comment]
> > > I see fix for « Availability Sync » Is not good for me 😂 I want keep histories in overseerr I create new value in db for keep already downloaded Working in progress
> > 
> > 
> > Don't put in the effort as its already done in this PR: #3460 which will be merged at some point.
> > As for this PR, I don't think this belongs in Overseerr. Sonarr normally grabs new seasons automatically when a show is monitored, and they will appear in Plex.
> 
> Personally, I don't use Sonarr. I've created my own script that fetches TV shows and movies. I just think it would be much better to have this view in Overseerr, as I prefer to have all graphical interactions with Overseerr. I don't want to manage my lists of movies and TV shows in two different programs... especially since I don't necessarily want to download all available seasons. Anyway, I'll incorporate the work from the MR for the deleted status. Thank you.

Overseerr is built for Radarr/Sonarr. We can't accommodate everyone's personal use-cases, especially custom scripts.

Even if we ignore the part where I don't believe this PR works in Overseerr, you are doing things like saving to the DB when loading discovery sliders, and there are tons of nested queries.

I'm sorry but I just don't see this PR working out.

**Comment by cedric-bour** [comment]
> > > > Je vois un correctif pour « Availability Sync » N'est pas bon pour moi 😂 Je veux garder les historiques dans overseerr Je crée une nouvelle valeur dans db pour garder déjà téléchargé Travail en cour
> > > 
> > > 
> > > Ne faites pas l'effort comme cela a déjà été fait dans ce PR : [#3460 ](https://github.com/sct/overseerr/pull/3460)qui sera fusionné à un moment donné.En ce qui concerne ce PR, je ne pense pas que cela appartienne à Overseerr. Sonarr saisit normalement automatiquement les nouvelles saisons lorsqu'une émission est surveillée, et elles apparaîtront dans Plex.
> > 
> > 
> > Personnellement, je n'utilise pas Sonarr. J'ai créé mon propre script qui récupère des émissions de télévision et des films. Je pense juste qu'il serait beaucoup mieux d'avoir ce point de vue dans Overseerr, car je préfère avoir toutes les interactions graphiques avec Overseerr. Je ne veux pas gérer mes listes de films et d'émissions de télévision dans deux programmes différents... d'autant plus que je ne veux pas nécessairement télécharger toutes les saisons disponibles. Quoi qu'il en soit, je vais intégrer le travail du MR pour le statut supprimé. Merci.
> 
> Overseerr est construit pour Radarr/Sonarr. Nous ne pouvons pas accueillir les cas d'utilisation personnels de tout le monde, en particulier les scripts personnalisés.
> 
> Même si nous ignorons la partie où je ne crois pas que ce PR fonctionne dans Overseerr, vous faites des choses comme l'enregistrement dans la base de données lors du chargement des curseurs de découverte, et il y a des tonnes de requêtes imbriquées.
> 
> Je suis désolé, mais je ne vois tout simplement pas ces relations publiques fonctionner.



> > > > I see fix for « Availability Sync » Is not good for me 😂 I want keep histories in overseerr I create new value in db for keep already downloaded Working in progress
> > > 
> > > 
> > > Don't put in the effort as its already done in this PR: #3460 which will be merged at some point.
> > > As for this PR, I don't think this belongs in Overseerr. Sonarr normally grabs new seasons automatically when a show is monitored, and they will appear in Plex.
> > 
> > 
> > Personally, I don't use Sonarr. I've created my own script that fetches TV shows and movies. I just think it would be much better to have this view in Overseerr, as I prefer to have all graphical interactions with Overseerr. I don't want to manage my lists of movies and TV shows in two different programs... especially since I don't necessarily want to download all available seasons. Anyway, I'll incorporate the work from the MR for the deleted status. Thank you.
> 
> Overseerr is built for Radarr/Sonarr. We can't accommodate everyone's personal use-cases, especially custom scripts.
> 
> Even if we ignore the part where I don't believe this PR works in Overseerr, you are doing things like saving to the DB when loading discovery sliders, and there are tons of nested queries.
> 
> I'm sorry but I just don't see this PR working out.

Your decision... :)

Just to let you tell, this code can definitely be optimized, and this merge is a concept.

I'll hold it for myself. However, if you decide to include it in the future (with your code), it could be highly beneficial for many people, I believe.

**Pull request closed without merging**
