### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cron410**
#### Description
Added   `--name overseerr` to the `docker run` command so `docker stop overseerr` and `docker rm overseerr` work as expected when running a manual update.

#### To-Dos

- [ ] Successful build `yarn build`
- [ ] Translation keys `yarn i18n:extract`
- [ ] Database migration (if required)

### CODE REVIEW

**Comment by TheCatLady** [comment]
We should update the examples in `/docs/getting-started/installation.md` as well. 😺

**Comment by sct** [comment]
@cron410 any update on this? need the other docs updated as well.

**Comment by cron410** [comment]
It's on my to-do list for sure.

**Review by cron410 — COMMENTED** [review]
Requested additions completed.

**Comment by TheCatLady** [comment]
> Requested additions completed.

LGTM, can you rebase?

**Review by TheCatLady — APPROVED** [review]

**Pull request merged**
