### PR TITLE
fix: allow blank issue descriptions

### PR DESCRIPTION
**Pull request by kirsch33**
#### Description
This PR allows blank/empty issue descriptions to be submitted and removes the "*" required label on the modal form.

#### To-Dos

- [ ] Successful build `yarn build`
- [ ] Translation keys `yarn i18n:extract`
- [ ] Database migration (if required)

#### Issues Fixed or Closed

- partially addresses https://github.com/sct/overseerr/issues/3580

### CODE REVIEW

**Comment by danshilm** [comment]
More changes are required for this to be properly implemented; an issue comment is still created for the issue, just with an empty text. The endpoint to create issues needs to be modified to accept Issues without comments.

**Comment by kirsch33** [comment]
I don't follow. In my testing this performs exactly as intended. As issue is created without any comments and with a blank description. 

After peeking around the code base some I still don't see what else would need to be modified. Can you provide a bit more info as to what endpoint needs to be modified ?

**Comment by sct** [comment]
I would also not like to encourage people to not leave comments. I think they can spend a small amount of time writing in what the issue is.

**Comment by kirsch33** [comment]
@sct in my case I have an external program that operates via webhooks and looks for subtitles issues. If found it initiates a sync.

Its much easier to explain to family/friends that they simply need to click the issue button and change the type to "subtitle" versus asking them to also describe that its out of sync (since that's the only possible subtitle related issue at least with my specific setup it is redundant). Kind of a niche situation, but that's what lead to this PR.

Anyways, if this doesn't jive with the vision for Overseerr, I understand.

**Comment by sct** [comment]
> @sct in my case I have an external program that operates via webhooks and looks for subtitles issues. If found it initiates a sync.
> 
> Its much easier to explain to family/friends that they simply need to click the issue button and change the type to "subtitle" versus asking them to also describe that its out of sync (since that's the only possible subtitle related issue at least with my specific setup it is redundant). Kind of a niche situation, but that's what lead to this PR.
> 
> Anyways, if this doesn't jive with the vision for Overseerr, I understand.

That's a really cool use-case! I love the idea but unfortunately I would still like to avoid making this optional (For my own sanity, and probably many others). For now I think best to just let your users know they should just write in literally any text in the description field. Hopefully that's not too much of a bother.

**Comment by kirsch33** [comment]
@sct not at all, I understand. Thank you for your time and for Overseerr itself.

**Comment by Lockszmith-GH** [comment]
Sorry to ressurrect this, but how about a default description when subtitle is selected?

**Pull request closed without merging**
