### PR TITLE
feat(pwa): add shortcuts to PWA

### PR DESCRIPTION
**Pull request by danshilm**
#### Description
Adds shortcuts to the Requests, Users and Settings pages.

#### Screenshot (if UI-related)
Example on Windows:
image

#### To-Dos

- [x] Successful build `yarn build`

#### Issues Fixed or Closed

- Fixes none

### CODE REVIEW

**Comment by sct** [comment]
My issue with this is non-admins will also see the users/settings links (And they just won't work.)

Maybe instead of users/settings we can add Profile/Settings (but the users settings)?

**Comment by TheCatLady** [comment]
Pretty sure you can use SVG icons in the manifest :)

**Comment by danshilm** [comment]
> 
> 
> My issue with this is non-admins will also see the users/settings links (And they just won't work.)
> 
> Maybe instead of users/settings we can add Profile/Settings (but the users settings)?

Ah yes, I didn't think about that.
Sounds good, I'll make the change.

**Comment by danshilm** [comment]
> 
> 
> ~Pretty sure you can use SVG icons in the manifest :)~ Scratch that, Chrome doesn't support SVG here apparently. 😿 https://web.dev/app-shortcuts/#icons-(optional)
> 
> That said:
> 
> > If you want pixel-perfect icons, provide them in increments of 48dp (i.e. 36x36, 48x48, 72x72, 96x96, 144x144, 192x192 pixel icons). Otherwise, it is recommended that you use a single 192x192 pixel icon.

192x192 px it is 😄

**Review by sct — APPROVED** [review]
LGTM 💯 Thanks!

**Pull request merged**
