### PR TITLE
feat(plex): refresh token schedule

### LINKED ISSUE #3861: Add API ping to refresh Plex authentication token
### Description

Overseerr users currently have to log in periodically to refresh the authentication token for plex that allows watchlist sync. I've been alerted to the existence of a [ping function in the MyPlex module](https://python-plexapi.readthedocs.io/en/latest/modules/myplex.html#plexapi.myplex.MyPlexAccount.ping) that will refresh this token to prevent it from expiring.

### Desired Behavior

Implementation of the MyPlex module's ping function for automatic refresh of Plex authorization token so that users do not have to periodically sign in for their Plex watchlist to sync with Overseerr.

### Additional Context

image

image

image

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

### PR DESCRIPTION
**Pull request by DamsDev1**
#### Description
Add API ping to refresh Plex authentification token

#### To-Dos

- [X] Successful build `yarn build`
- [X] Translation keys `yarn i18n:extract`
- [N/A] Database migration (if required)

#### Issues Fixed or Closed

- Fixes #3861

### CODE REVIEW

**Comment by DrWatson** [comment]
This has been something I have struggled with for a long time now. Loving that this is getting implemented.

**Comment by DrWatson** [comment]
Is there a plan for getting this feature added?

**Comment by dmudgeau** [comment]
I'm so glad too this is being implemented Ive told my users if they ever add something to their Plex watchlist and it doesn't request to let me know but they never do lol

is there a way to track this issue so we get a notification when it's been implemented in the latest build?

cheers

**Comment by OwsleyJr** [comment]
Looks good! Time to merge. Thanks for the PR :)

**Review by OwsleyJr — APPROVED** [review]

**Comment by OwsleyJr** [comment]
@all-contributors please add @DamsDev1 for code

**Pull request merged**
