### PR TITLE
feat: auto tagging requested media with username

### PR DESCRIPTION
**Pull request by IzaacJ**
#### Description
Relating to discussion: https://github.com/sct/overseerr/discussions/3313
Adding an option to the Radarr and Sonarr service to enable automatic tagging with the username requesting the media.
Current format, to reduce tag clutter if a user changes displayname: `[user.id] - [user.displayName]`

#### To-Dos

- [x] Successful build `yarn build`
- [x] Translation keys `yarn i18n:extract`
- [ ] Database migration (if required)

#### Issues Fixed or Closed

- #1964

### CODE REVIEW

**Comment by sct** [comment]
Thanks for making this! I know a lot of people will find this valuable. @TheCatLady can you check the language strings?

**Review by TheCatLady — CHANGES_REQUESTED** [review]
I think the setting should appear immediately below the "Tags" setting so that the related options are grouped together.

Here's my suggestion for the text (see other settings pages for examples of the styling, and note that the secondary/"tip" text does not have a period at the end):

image

**Comment by IzaacJ** [comment]
Great! I'll fix that later this week 🙂

**Comment by MrDynamo** [comment]
> Great! I'll fix that later this week 🙂

Any progress on the update? I would like to see this feature implemented to make managing the library more efficient!

**Comment by sct** [comment]
> Great! I'll fix that later this week 🙂

Any chance you still want to work on this? We can maybe take over otherwise. Let us know!

**Review by sct — APPROVED** [review]

**Comment by sct** [comment]
@all-contributors please add @IzaacJ for code

**Comment by sct** [comment]
@holopin-bot @IzaacJ heres a pin!

**Comment by sbressler** [comment]
FYI, looks like https://docs.overseerr.dev/using-overseerr/settings#radarr-sonarr-settings needs an update to add mention/explanation of this setting.

**Pull request merged**
