### PR TITLE
feat: Topic Support for Telegram Notifications 

### LINKED ISSUE #3389: Add support for Telegram topics
### Description

Topics are new in telegram, and allow like discord to create several channels/topics to organize notifications. Currently it's not possible to use them and all notifications arrive in one and the same chat.

### Desired Behavior

An input field for the `message_thread_id` in addition to the `chatId` that already exists
Since version 6.4 of Telegram Bot API, they added the `message_thread_id` to choose the topic in which to send the message: https://core.telegram.org/bots/api#december-30-2022
You have to make this field optional, because you can use a group without the topics.

### Additional Context

Tautulli has just implemented it in the latest version following this issue: https://github.com/Tautulli/Tautulli/issues/1980
How to get the message_thread_id https://stackoverflow.com/questions/74773675/how-to-get-topic-id-for-telegram-group-chat
I just created the same feature request at Sonarr and Radarr : https://github.com/Sonarr/Sonarr/issues/5486 / https://github.com/Radarr/Radarr/issues/8199

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

### PR DESCRIPTION
**Pull request by npkevin**
#### Screenshot (if UI-related)
image

#### To-Dos

- [x] Successful build `yarn build`
- [x] Translation keys `yarn i18n:extract`

#### Issues Fixed or Closed

- Fixes #3389

### CODE REVIEW

**Comment by Flashky** [comment]
I really need this feature on Jellyseerr.

**Comment by VozDeOuro** [comment]
Im very interested in this, looks great. Can we expect this merge anytime soon?

**Comment by samirsaliba** [comment]
@npkevin Any updates on this? is there still interest in this feature? My friends and I would appreciate it a lot

**Comment by UnbreakableKid** [comment]
Also very interested

**Comment by VozDeOuro** [comment]
I did a fork that add a second telegram agent and add a thread option, It is poorly implemented so that is why I do not do a PR request, but If you guys want to use it, I'm using it and its working 

here is the fork https://github.com/VozDeOuro/overseerr-telegram

any doubt dm me on discord: vozdeouro
image

**Comment by sannidhyaroy** [comment]
Is this still in WIP?

**Comment by JshGrn** [comment]
Why has this been closed?

**Pull request closed without merging**
