### PR TITLE
Adding link with Fail2ban tutorial to the homepage

### PR DESCRIPTION
**Pull request by costaht**
#### Description

Adding link with Fail2ban tutorial to the homepage

### CODE REVIEW

**Comment by TheCatLady** [comment]
Shouldn't this be a part of #739?  You can just commit it to the same branch as the other changes, and it'll add it to your existing PR.

**Comment by costaht** [comment]
Sorry, I'm not familiar with github workflow and i don't know how to do that.

**Comment by TheCatLady** [comment]
@costaht If you're using the web interface, just edit the file here: https://github.com/costaht/overseerr/blob/develop/docs/SUMMARY.md

**Comment by costaht** [comment]
Moving to #739

**Pull request closed without merging**
