### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/overseerr/overseerr-frontend/) for Overseerr/Overseerr Frontend.

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by sct — APPROVED** [review]

**Comment by TheCatLady** [comment]
@all-contributors please add @Dabu-dot for translation

**Comment by TheCatLady** [comment]
@all-contributors please add @comradekingu for translation

**Comment by comradekingu** [comment]
@TheCatLady 
I had my name removed from the contributors already.
Don't agree with there being a CoC. Just trying to keep the nb_NO resource on Weblate free of errors.
Would otherwise obviously finish the whole translation and keep contributing.
Luckily CoCs and the covenant CoC especially is falling out of fashion quickly now, so I hope to see you again at the other end.

**Comment by TheCatLady** [comment]
@comradekingu Ah sorry, I had no idea! Closed the PR. Thanks for your contributions!

**Pull request merged**
