### PR TITLE
feat(login): add oidc login option

### LINKED ISSUE #1638: Login with other services
#### Description

Is your feature request related to a problem? If so, please provide a clear and concise description of the problem. E.g., "I'm always frustrated when [...]."

I have some family members who I would like to give access to but will probably result in me being constantly asked for their password. Adding support for providers like auth0 would allow me to enable sending a code via sms or email for them to enter on the page to login as an authentication method which would work better than a link if the web app is added to their home screen.

#### Desired Behavior

Allow a third party authentication service like auth0 to either login directly to the web app similar to plex or using SSO from a reverse proxy.

### PR DESCRIPTION
**Pull request by ankarhem**
#### Description
Adds support for a OIDC Identity Provider

TODO:
- [ ] dont load settings in middleware (why does this run before settings is loaded?)
- [ ] hide login button if not enabled

#### Screenshot (if UI-related)
https://cln.sh/wGbPIdYUKas2QId0cqxw

#### To-Dos

- [x] Successful build `yarn build`
- [ ] Translation keys `yarn i18n:extract`
- [ ] Database migration (if required)

#### Issues Fixed or Closed

- Fixes #1638

### CODE REVIEW

**Comment by lukasmrtvy** [comment]
@sct ping

**Comment by sct** [comment]
> @sct ping

Um?

**Comment by lenaxia** [comment]
I'm guessing they pinged because authelia has completed the core implementation of oidc and so could be worth implementing on this side now too. It's something I'd like to help with but my coding days are long in the past.

**Comment by Emalton** [comment]
Is there a reason why this was closed? Would like to potentially help out. Thanks!

**Comment by Cookie-Monster-Coder** [comment]
Idk but I would recommend to look at https://github.com/Fallenbagel/jellyseerr

It's a hard fork of Overseer that includes support for both Jellyfin and Plex. The devs for Jellyseerr are more open to ideas and are really helpful.

**Pull request closed without merging**
