### PR TITLE
build: extension the dockerignore

### PR DESCRIPTION
**Pull request by doob187**
#### Description
Extension of the dockerignore file, .md files excluded, yml files excluded, Dockerfile excluded

#### Screenshot (if UI related)

Not needed

#### Todos

- [x] Sucessfully builds `yarn build`
- [x] Translation Keys `yarn i18n:extract`
- [ ] Database migration created (if required)

#### Issues Fixed or Closed by this PR

No

### CODE REVIEW

**Comment by sct** [comment]
This should be `build:` not `fix:`

**Comment by doob187** [comment]
Kk let me fix this one

**Comment by sct** [comment]
The PR title and the commit messages are two different things. Its the actual commit messages that need to follow the convention. Either way, I can overwrite it when I squash & merge.

Can you rebase this again? Thanks.

**Review by sct — APPROVED** [review]

**Comment by doob187** [comment]
Done

**Comment by sct** [comment]
@all-contributors please add @doob187 for infra

**Pull request merged**
