### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Overseerr/Overseerr Frontend](https://hosted.weblate.org/projects/overseerr/overseerr-frontend/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by TopperBG** [comment]
Bump ?

**Review by OwsleyJr — APPROVED** [review]

**Comment by merquel** [comment]
@sct @TheCatLady Would be great if you could take a look at this when you have time. Been a while since the translations were updated.

**Comment by merquel** [comment]
@OwsleyJr It seems like @sct @TheCatLady are inactive at the moment. What can we do to get this merged?

**Comment by TopperBG** [comment]
> @OwsleyJr It seems like @sct @TheCatLady are inactive at the moment. What can we do to get this merged?

Or the project is abandoned ?

**Comment by jordanjones98** [comment]
@sct from what I understand these PR's are made after translations are approved (by you I assume). Is it worth auto merging weblate PR's with a passing build?

**Comment by sct** [comment]
> @sct from what I understand these PR's are made after translations are approved (by you I assume). Is it worth auto merging weblate PR's with a passing build?

Historically we have wanted to check this MR for glaring issues but with our lack of resources lately it might be worth considering auto merging these. 🤔

**Pull request merged**
