### PR TITLE
Add healthcheck to dockerfile

### PR DESCRIPTION
**Pull request by modem7**
#### Description

Add healthcheck to dockerfile

#### Screenshot (if UI-related)

image

### CODE REVIEW

**Comment by TheCatLady** [comment]
I'm not sure how I feel about this..  Healthchecks can result in a lot of syslog spam, and so I kinda think that this should be opt-in (define the check yourself in your `docker run` command or Compose file) rather than opt-out (defining the check in the `Dockerfile` and forcing users to disable the checks).

**Comment by modem7** [comment]
> I'm not sure how I feel about this..  Healthchecks can result in a lot of syslog spam, and so I kinda think that this should be opt-in (define the check yourself in your `docker run` command or Compose file) rather than opt-out (defining the check in the `Dockerfile` and forcing users to disable the checks).

In this particular case, wget is set to quiet and sends any logs to dev/null. There shouldn't be any spam.

**Comment by TheCatLady** [comment]
Even if we disable logging from the healthcheck, there's also moby/moby#42200.

**Comment by TheCatLady** [comment]
Sorry @modem7, discussed this with @sct and we aren't going to be merging this.  Anyone who wants the healthcheck should define it themselves.

**Comment by Krojack** [comment]
Curl is the most commonly used command to use for healchecks via compose file and it's not even included with the image.

**Comment by Salvora** [comment]
image has wget in it so, this works for a good healthcheck in compose

```yaml
    healthcheck:
      test:
        ["CMD", "wget", "--spider", "-q", "http://localhost:5055/api/v1/status"]
      start_period: 10s
      interval: 30s
      timeout: 20s
      retries: 3
```

**Comment by modem7** [comment]
> image has wget in it so, this works for a good healthcheck in compose
> 
> ```yaml
>     healthcheck:
>       test:
>         ["CMD", "wget", "--spider", "-q", "http://localhost:5055/api/v1/status"]
>       start_period: 10s
>       interval: 30s
>       timeout: 20s
>       retries: 3
> ```

That's similar to what I've put in the PR:

```dockerfile
HEALTHCHECK --interval=30s --timeout=10s --retries=3 --start-period=10s \
    CMD wget http://localhost:5055/api/v1/status -qO /dev/null || exit 1
```

And for my compose:

```yaml
    healthcheck:
      test: wget http://localhost:5055/api/v1/status -qO /dev/null || exit 1
      interval: 30s
      retries: 3
```

**Pull request closed without merging**
